name: test_env
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - matplotlib
  - pandas
  - bokeh
  - dask
  - distributed
  - dipy
  - h5py
  - graphviz
  - python-graphviz
  - pip
  - pip:
    - SimpleITK